 export const countries:Array<string> = [
    "Afghanistan",
    "Australia",
    "Austria",
    "Bangladesh",
    "Brazil",
    "Cambodia",
    "Canada",
    "Dominica",
    "Egypt",
    "France",
    "Germany",
    "Honduras",
    "India",
    "Indonesia",
    "Japan",
    "Malaysia",
    "Maldives",
    "Netherlands",
    "Pakistan",
    "South Africa",
    "South Korea",
    "Sri Lanka",
    "Switzerland",
    "Thailand",
    "Zambia",
   
 ]
